site_name: My MkDocs Material Documentation
site_url: https://sitename.example
theme:
  name: material
  features:
    - navigation.footer
  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
    
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  
